spring.application.name=school
#server.port=9999
spring.datasource.url= jdbc:postgresql://localhost:5432/hogwarts
#spring.datasource.username= student
#spring.datasource.password= chocolatefrog
spring.datasource.username=bot_user
spring.datasource.password=bot_password

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= validate

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

avatar.dir.path=images/avatar

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

spring.profiles.active=prod
